/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Beans.Apartamento;
import Beans.Condominio;
import Beans.Locador;
import Dao.DAOApartamento;
import Dao.DAOLocador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ismae
 */
public class FormApartamento extends javax.swing.JFrame {

    /**
     * Creates new form FormApartamento
     */
    public FormApartamento() {
        initComponents();
        readJTable();
    }
     public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) this.masterTable.getModel();
        modelo.setNumRows(0);
        DAOApartamento dao = new DAOApartamento();
        for (Apartamento ap : dao.findAll()) {
            modelo.addRow(new Object[]{
                ap.getId(),
                ap.getQtdQuarto(),
                ap.getEstado(),
                ap.getCondominio().getId(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        qtdQuartoLabel = new javax.swing.JLabel();
        qtdQuartoField = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        estadoField = new javax.swing.JTextField();
        idCondominioLabel = new javax.swing.JLabel();
        idCondominioField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        masterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "QTD Quartos", "Estado", "id Condominio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterScrollPane.setViewportView(masterTable);

        qtdQuartoLabel.setText("Qtd Quarto:");

        estadoLabel.setText("Estado:");

        idCondominioLabel.setText("Id Condominio:");

        newButton.setText("Cadastra");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Excluir");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Alterar");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtdQuartoLabel)
                            .addComponent(estadoLabel)
                            .addComponent(idCondominioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(qtdQuartoField, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(estadoField, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(idCondominioField, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdQuartoLabel)
                    .addComponent(qtdQuartoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCondominioLabel)
                    .addComponent(idCondominioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        if (!this.qtdQuartoField.getText().equals("") && !this.estadoField.getText().equals("") && !this.idCondominioField.getText().equals("") ) {

            Apartamento ap = new Apartamento();
            Condominio c = new Condominio();
            ap.setEstado(this.estadoField.getText());
            ap.setQtdQuarto(Integer.parseInt(this.qtdQuartoField.getText()));
            c.setId(Integer.parseInt(this.idCondominioField.getText()));
            ap.setCondominio(c);            
            DAOApartamento dao = new DAOApartamento();            
            dao.save(ap);
            this.qtdQuartoField.setText("");
            this.estadoField.setText("");
            this.idCondominioField.setText("");
            readJTable();
            JOptionPane.showMessageDialog(null,"cadastrado com sucesso");

        }else{
            JOptionPane.showMessageDialog(null, "Por favor preencher todos os campos para realizar o cadastro");
        }
    }//GEN-LAST:event_newButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (this.masterTable.getSelectedRow() != -1) {
           Apartamento ap = new Apartamento();
            //vai pegar o valor da linha selecionada
            ap.setId((int) this.masterTable.getValueAt(this.masterTable.getSelectedRow(), 0));

            DAOApartamento dao = new DAOApartamento();
            dao.delete(ap);
            readJTable();
            JOptionPane.showMessageDialog(null,"Excluido com sucesso");            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        if (this.masterTable.getSelectedRow() != -1) {
            Apartamento ap = new Apartamento();
            //vai pegar o valor da linha selecionada
            ap.setId( Integer.parseInt(this.masterTable.getValueAt(this.masterTable.getSelectedRow(), 0).toString()));
            ap.setQtdQuarto(Integer.parseInt(this.masterTable.getValueAt(this.masterTable.getSelectedRow(), 1).toString()));
            ap.setEstado(this.masterTable.getValueAt(this.masterTable.getSelectedRow(), 2).toString());
            Condominio c = new Condominio(Integer.parseInt( this.masterTable.getValueAt(this.masterTable.getSelectedRow(), 3).toString()));
            ap.setCondominio(c);
            
            DAOApartamento dao = new DAOApartamento();
            dao.update(ap);
            readJTable();
            JOptionPane.showMessageDialog(null,"Alterado com sucesso");
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormApartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField estadoField;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField idCondominioField;
    private javax.swing.JLabel idCondominioLabel;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField qtdQuartoField;
    private javax.swing.JLabel qtdQuartoLabel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
